# Generated by Django 3.1.4 on 2020-12-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('blog', '0003_auto_20190907_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6),
        ),
    ]
